const RecipesActionTypes = {
  FETCH_RECIPES_START: 'FETCH_RECIPES_START',
  FETCH_RECIPES_SUCCESS: 'FETCH_RECIPES_SUCCESS',
  FETCH_RECIPES_FAILURE: 'FETCH_RECIPES_FAILURE',
}

export default RecipesActionTypes
